services:
  psql:
    image: postgres:17
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=chatloid
    volumes:
      - chatloid-data:/var/lib/postgresql/data

  mongodb:
    image: mongodb/mongodb-community-server:8.2-ubi8
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
    volumes:
      - chatloid-message-data:/data/db

volumes:
  chatloid-data:
  chatloid-message-data:
